### ISSUE TITLE
plugin-http-file-cost-datasource

### ISSUE THREAD

**Issue by stat-kwon** [cloudforet-io/tsc#6]
### Plugin contact emails

seolmin@mz.co.kr

### Project Summary

Data source plugin for file by requesting HTTP

### Project Description

Each on-premise environment has a different form of cost management. 
Accordingly, we need a plugin that can fetch the file via HTTP request and normalize the fetched cost file.

### Product Introduction URL

https://github.com/cloudforet-io/plugin-http-file-cost-datasource

### Product API URL

https://github.com/cloudforet-io/plugin-http-file-cost-datasource

### Contributing or Sponsoring Org

Megazone Cloud

### IP Policy

- [X] If the project is accepted, I agree the project will follow the Cloudforet IP Policy

### Why Cloudforet?

Each on-premise environment has a different form of cost management. 
Accordingly, we need a plugin that can fetch the file via HTTP request and normalize the fetched cost file.

### Benefit to the Landscape

[cost-analysis](https://github.com/cloudforet-io/cost-analysis)

### Project Advisor

jihyung Song

**Comment by choonho** [comment]
Move development issue to cloudforet repository issue
